### ISSUE TITLE
Error: Error: Attempt to postMessage on disconnected port

### ISSUE THREAD

**Issue by gurucubano** [browserpass/browserpass-extension#159]
### General information

-   FreeBSD 12-CURRENT amd64
-   Browser + version: FF 64.0
-   Information about the host app:
    -   How did you install it?
         
     compiled by my own from git clone ...
    -   If installed an official release, put a version (`$ browserpass --version`):
browserpass-freebsd64 --version
Browserpass host app version: 3.0.6

    -   If built from sources, put a commit id (`$ git describe --always`):
git describe --always
faaa99f

-   Information about the browser extension:
    -   How did you install it?
        
    -   Browserpass extension version as reported by your browser:
I have two: The old 1.0.5 (which still works)
The new 3.1.1 which givew the error

---

If you are getting an error immediately after opening popup, have you followed the [Configure browsers](https://github.com/browserpass/browserpass-native#configure-browsers) documentation section?

---
I did:
### Exact steps to reproduce the problem
```


$ git clone https://github.com/browserpass/browserpass-native.git 
$ cd browserpass-native/
$ git show
commit faaa99feb4423739a3c176a5759f4d2fb038b12f (HEAD -> master, origin/master, origin/HEAD)
Author: Maxim Baz <github@maximbaz.com>
Date:   Sat Jun 29 19:09:42 2019 +0200
...

$ gmake BIN=browserpass-freebsd64 PREFIX=/usr/local configure
/usr/bin/sed -i 's|"path": ".*"|"path": "'"/usr/local/bin/browserpass-freebsd64"'"|' browser-files/chromium-host.json
sed: 1: "browser-files/chromium- ...": undefined label 'rowser-files/chromium-host.json'
gmake: *** [Makefile:98: configure] Error 1

$ gmake BIN=browserpass-freebsd64 PREFIX=/usr/local browserpass-freebsd64
env GOOS=freebsd GOARCH=amd64 go build -ldflags "-extldflags " -gcflags "all=-trimpath=/home/guru/browserpass/browserpass-native" -asmflags "all=-trimpath=/home/guru/browserpass/browserpass-native" -o browserpass-freebsd64
[guru@c720-r342378 ~/browserpass/browserpass-native]$ ls -l browserpass-freebsd64 
-rwxr-xr-x  1 guru  wheel  4120619 19 ago.  05:44 browserpass-freebsd64

# gmake BIN=browserpass-freebsd64 PREFIX=/usr/local install
/usr/local/bin/ginstall -Dm755 -t "/usr/local/bin/" browserpass-freebsd64
/usr/local/bin/ginstall -Dm644 -t "/usr/local/lib/browserpass/" Makefile
/usr/local/bin/ginstall -Dm644 -t "/usr/local/share/licenses/browserpass/" LICENSE
/usr/local/bin/ginstall -Dm644 -t "/usr/local/share/doc/browserpass/" README.md
/usr/local/bin/ginstall -Dm644 browser-files/chromium-host.json   "/usr/local/lib/browserpass/hosts/chromium/com.github.browserpass.native.json"
/usr/local/bin/ginstall -Dm644 browser-files/chromium-policy.json "/usr/local/lib/browserpass/policies/chromium/com.github.browserpass.native.json"
/usr/local/bin/ginstall -Dm644 browser-files/firefox-host.json    "/usr/local/lib/browserpass/hosts/firefox/com.github.browserpass.native.json"

# cat /usr/local/lib/browserpass/hosts/firefox/com.github.browserpass.native.json
{
    "name": "com.github.browserpass.native",
    "description": "Browserpass native component for the Firefox extension",
    "path": "%%replace%%",
    "type": "stdio",
    "allowed_extensions": ["browserpass@maximbaz.com"]
}

# ls -l /usr/local/bin/browserpass-freebsd64
-rwxr-xr-x  1 root  wheel  4120619 19 ago.  05:45 /usr/local/bin/browserpass-freebsd64

# vim /usr/local/lib/browserpass/hosts/firefox/com.github.browserpass.native.json
--> "path": "/usr/local/bin/browserpass-freebsd64",

restart firefox FF 64.0 (64-bit)

Ctrl-Shift-L or click on (?) icon gives:
Error: Error: Attempt to postMessage on disconnected port
```
Btw: The old extension still works fine and uses the password-store fine.

**Comment by gurucubano** [comment]
It seems, I fixed it with:
```
# mkdir -p /usr/local/lib/mozilla/native-messaging-hosts/
# cp -p /usr/local/lib/browserpass/hosts/firefox/com.github.browserpass.native.json /usr/local/lib/mozilla/native-messaging-hosts/com.github.browserpass.native.json
```

**Comment by maximbaz** [comment]
Hey, the reason for the "configure" goal failed seems to be that you use gmake but you don't have gsed installed (or it's not in PATH), so it couldn't replace the path to the binary correctly. You correctly worked around that by manually editing json files with vim 👍

The reason extension showed an error immediately after pop-up was opened was because you missed the [Configuring browsers](https://github.com/browserpass/browserpass-native#configure-browsers) section (which was also mentioned in the issue template 😛), you correctly discovered manual steps that configure Firefox (by copying the necessary file to the correct folder). 

Seems everything is fine now? Enjoy your new extension! 🤘

**Comment by gurucubano** [comment]
El día domingo, agosto 18, 2019 a las 11:11:20p. m. -0700, Maxim Baz escribió:

> Hey, the reason for the "configure" goal failed seems to be that you use gmake but you don't have gsed installed (or it's not in PATH), so it couldn't replace the path to the binary correctly. You correctly worked around that by manually editing json files with vim 👍
> 

'gsed' is not standard on FreeBSD. If your make engine needs it, you
should check for it or request it in the readmes (Have I overlooked it?)
I installed it and with this the configure part works fine:

```
$ gmake BIN=browserpass-freebsd64 PREFIX=/usr/local configure
/usr/local/bin/gsed -i 's|"path": ".*"|"path": "'"/usr/local/bin/browserpass-freebsd64"'"|' browser-files/chromium-host.json
/usr/local/bin/gsed -i 's|"path": ".*"|"path": "'"/usr/local/bin/browserpass-freebsd64"'"|' browser-files/firefox-host.json
```

> The reason extension showed an error immediately after pop-up was opened was because you missed the [Configuring browsers](https://github.com/browserpass/browserpass-native#configure-browsers) section (which was also mentioned in the issue template 😛), you correctly discovered manual steps that configure Firefox (by copying the necessary file to the correct folder). 
> 

I did read this and followed it (I even re-run now the command from the
bash history). I don't know why it failed to put the file in place:

```
# gmake BIN=browserpass-freebsd64 PREFIX=/usr/local -n install
/usr/local/bin/ginstall -Dm755 -t "/usr/local/bin/" browserpass-freebsd64
/usr/local/bin/ginstall -Dm644 -t "/usr/local/lib/browserpass/" Makefile
/usr/local/bin/ginstall -Dm644 -t "/usr/local/share/licenses/browserpass/" LICENSE
/usr/local/bin/ginstall -Dm644 -t "/usr/local/share/doc/browserpass/" README.md
/usr/local/bin/ginstall -Dm644 browser-files/chromium-host.json   "/usr/local/lib/browserpass/hosts/chromium/com.github.browserpass.native.json"
/usr/local/bin/ginstall -Dm644 browser-files/chromium-policy.json "/usr/local/lib/browserpass/policies/chromium/com.github.browserpass.native.json"
/usr/local/bin/ginstall -Dm644 browser-files/firefox-host.json    "/usr/local/lib/browserpass/hosts/firefox/com.github.browserpass.native.json"
root@c720-r342378:/home/guru/browserpass/browserpass-native # ls -l /usr/local/lib/browserpass/hosts/firefox/com.github.browserpass.native.json
-rw-r--r--  1 root  wheel  254 19 ago.  05:49 /usr/local/lib/browserpass/hosts/firefox/com.github.browserpass.native.json
```

I will run the installation again on another fresh FreeBSD. Will take
some time because I'm now for vacation in Italy.

Thanks for your help and software, in any case.

	matthias

-- 
Matthias Apitz, ✉ guru@unixarea.de, http://www.unixarea.de/ +49-176-38902045
Public GnuPG key: http://www.unixarea.de/key.pub

**Comment by maximbaz** [comment]
> 'gsed' is not standard on FreeBSD. If your make engine needs it, you
should check for it or request it in the readmes (Have I overlooked it?)

Yep, in the [Install manually](https://github.com/browserpass/browserpass-native#install-manually) section 🙂 

> If you are on FreeBSD, first install the GNU tools: `pkg install coreutils gmake gsed`. Use `gmake` in place of `make` below.

-----

> I did read this and followed it (I even re-run now the command from the
bash history). I don't know why it failed to put the file in place:
> `# gmake BIN=browserpass-freebsd64 PREFIX=/usr/local -n install`

You are referring to a different command, [Configure browsers](browserpass/browserpass-native#configure-browsers) section is not about `make install`, it's about configuring specific browsers that you want to use. In your case you want Firefox, so you should run `make hosts-firefox-user` or `sudo make hosts-firefox`.

----------

> I will run the installation again on another fresh FreeBSD. Will take
some time because I'm now for vacation in Italy.

Enjoy the vacation! 🏖️

**Comment by gurucubano** [comment]
Hey, what does it mean when the browserpass icon (that small key) has a
grey area with the number '1' in it? Thanks

	matthias
-- 
Matthias Apitz, ✉ guru@unixarea.de, http://www.unixarea.de/ +49-176-38902045
Public GnuPG key: http://www.unixarea.de/key.pub

**Comment by maximbaz** [comment]
It means you have exactly one password entry in your password store that matches this specific website :)
